"""create tables

Revision ID: 1d0fc92ee1b6
Revises: 
Create Date: 2023-04-19 12:01:24.712380

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d0fc92ee1b6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('players',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('_password_hash', sa.String(), nullable=True),
    sa.Column('player_image', sa.String(), nullable=True),
    sa.Column('total_wins', sa.Integer(), nullable=True),
    sa.Column('total_games', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('image', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('games',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('playerA', sa.Integer(), nullable=True),
    sa.Column('playerB', sa.Integer(), nullable=True),
    sa.Column('ended', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['playerA'], ['players.id'], ),
    sa.ForeignKeyConstraint(['playerB'], ['players.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('game_tiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=True),
    sa.Column('tile_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.ForeignKeyConstraint(['tile_id'], ['tiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('game_tiles')
    op.drop_table('games')
    op.drop_table('tiles')
    op.drop_table('players')
    # ### end Alembic commands ###
