"""trying

Revision ID: 46c9a2ce5207
Revises: 
Create Date: 2023-04-17 16:01:17.699104

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46c9a2ce5207'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('games',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('players',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('_password_hash', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('values', sa.Integer(), nullable=True),
    sa.Column('suits', sa.String(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('game_id', sa.Integer(), nullable=True),
    sa.Column('card_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['card_id'], ['cards.id'], name=op.f('fk_cards_card_id_cards')),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], name=op.f('fk_cards_game_id_games')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('in_plays',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=True),
    sa.Column('card_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['card_id'], ['cards.id'], name=op.f('fk_in_plays_card_id_cards')),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], name=op.f('fk_in_plays_game_id_games')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pgts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=True),
    sa.Column('card_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['card_id'], ['cards.id'], name=op.f('fk_pgts_card_id_cards')),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], name=op.f('fk_pgts_game_id_games')),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pgts')
    op.drop_table('in_plays')
    op.drop_table('cards')
    op.drop_table('players')
    op.drop_table('games')
    # ### end Alembic commands ###
